CREATE TABLE `embryo_transfers` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `job_id` int(11) DEFAULT NULL,
  `embryo_resus_id` int(11) DEFAULT NULL,
  `ivf_id` int(11) DEFAULT NULL,
  `mmrrc_no` varchar(50) DEFAULT NULL,
  `bl_no` varchar(50) DEFAULT NULL,
  `pn_cr_no` varchar(50) DEFAULT NULL,
  `membership` varchar(100) DEFAULT NULL,
  `pts_ko_mo_no` varchar(50) DEFAULT NULL,
  `crispr` tinyint(1) DEFAULT NULL,
  `strain_name` varchar(100) DEFAULT NULL,
  `et_purpose` varchar(100) DEFAULT NULL,
  `investigator` varchar(100) DEFAULT NULL,
  `lab_contact` varchar(100) DEFAULT NULL,
  `background` varchar(100) DEFAULT NULL,
  `komp_clone` varchar(100) DEFAULT NULL,
  `et_date` date DEFAULT NULL,
  `et_lab` varchar(100) DEFAULT NULL,
  `et_time` time DEFAULT NULL,
  `expected_dob` date DEFAULT NULL,
  `et_by` varchar(100) DEFAULT NULL,
  `et_location` varchar(100) DEFAULT NULL,
  `fresh_frozen` varchar(25) DEFAULT NULL,
  `icsi_embryos` tinyint(1) DEFAULT NULL,
  `assisted_ivf_embryos` varchar(255) DEFAULT NULL,
  `save_pups` tinyint(1) DEFAULT NULL,
  `send_tails_to` varchar(25) DEFAULT NULL,
  `embryo_cryo_id` int(11) DEFAULT NULL,
  `recipient_strain` varchar(100) DEFAULT NULL,
  `anesthetic` varchar(100) DEFAULT NULL,
  `anesthetic_lot_no` varchar(25) DEFAULT NULL,
  `analgesic` varchar(100) DEFAULT NULL,
  `analgesic_lot_no` varchar(25) DEFAULT NULL,
  `comments` text,
  `maternity_updated_by` varchar(100) DEFAULT NULL,
  `pup_genotype_updated_by` varchar(100) DEFAULT NULL,
  `total_embryos_tx` int(11) DEFAULT NULL,
  `total_pups_born` int(11) DEFAULT NULL,
  `et_birth_rate` decimal(10,2) DEFAULT NULL,
  `total_male_pups` int(11) DEFAULT NULL,
  `total_female_pups` int(11) DEFAULT NULL,
  `total_mut_males` int(11) DEFAULT NULL,
  `total_mut_females` int(11) DEFAULT NULL,
  `et_total_mut_mice` int(11) DEFAULT NULL,
  `no_recipients` int(11) DEFAULT NULL,
  `no_litters` int(11) DEFAULT NULL,
  `litter_rate` decimal(10,2) DEFAULT NULL,
  `search` varchar(100) DEFAULT NULL,
  `primary_recharge` varchar(255) DEFAULT NULL,
  `secondary_recharge` varchar(255) DEFAULT NULL,
  `test_et_birth_rate` varchar(100) DEFAULT NULL,
  `no_total_chimeras` int(11) DEFAULT NULL,
  `no_total_male_chimeras` int(11) DEFAULT NULL,
  `no_total_female_chimeras` int(11) DEFAULT NULL,
  `chimeras_greater_than_fifty` int(11) DEFAULT NULL,
  `chimera_bl_no` int(11) DEFAULT NULL,
  `chimera_pn_no` int(11) DEFAULT NULL,
  `chimera_crispr` tinyint(1) DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `analgesic_dose` decimal(10,2) DEFAULT NULL,
  `anesthetic_dose` decimal(10,2) DEFAULT NULL,
  `analgesic_method` varchar(255) DEFAULT NULL,
  `anesthetic_method` varchar(255) DEFAULT NULL,
  `injection_id` int(11) DEFAULT NULL,
  `pups` varchar(10) DEFAULT NULL,
  `straw_label` varchar(25) DEFAULT NULL,
  `fmp_id_no` int(11) DEFAULT NULL,
  `fmp_job_id_no` int(11) DEFAULT NULL,
  `fmp_ivf_id_no` int(11) DEFAULT NULL,
  `fmp_rs_id_no` int(11) DEFAULT NULL,
  `embryo_transfer_day` varchar(255) DEFAULT NULL,
  `protocol` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`) USING BTREE,
  KEY `embryo_transfer_job` (`job_id`) USING BTREE,
  KEY `embryo_transfer_embryo_resus` (`embryo_resus_id`) USING BTREE,
  KEY `embryo_transfer_ivf` (`ivf_id`) USING BTREE,
  KEY `embryo_transfer_embryo_cryo` (`embryo_cryo_id`) USING BTREE,
  KEY `embryo_transfer_injection` (`injection_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=15190 DEFAULT CHARSET=utf8;


