CREATE TABLE `embryo_cryos` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `job_id` int(11) DEFAULT NULL,
  `ivf_id` int(11) DEFAULT NULL,
  `cryo_date` date DEFAULT NULL,
  `receiving_date` date DEFAULT NULL,
  `pi_or_mmrrc` varchar(255) DEFAULT NULL,
  `search` varchar(255) DEFAULT NULL,
  `background` varchar(255) DEFAULT NULL,
  `school` varchar(255) DEFAULT NULL,
  `stud_strain` varchar(255) DEFAULT NULL,
  `stud_id_no` varchar(255) DEFAULT NULL,
  `stud_dob` date DEFAULT NULL,
  `male_genotype` varchar(255) DEFAULT NULL,
  `female_strain_name` varchar(255) DEFAULT NULL,
  `no_females_used` int(11) DEFAULT NULL,
  `female_age` varchar(255) DEFAULT NULL,
  `female_genotype` varchar(255) DEFAULT NULL,
  `genotype_confirmed` tinyint(1) DEFAULT NULL,
  `donor_genotyped_by` varchar(255) DEFAULT NULL,
  `donor_genotyping_date` date DEFAULT NULL,
  `donor_genotype_comments` text,
  `fert_method` varchar(255) DEFAULT NULL,
  `ec_method` varchar(255) DEFAULT NULL,
  `ivf_by` varchar(255) DEFAULT NULL,
  `ec_by` varchar(255) DEFAULT NULL,
  `cryo_embryo_stage` varchar(255) DEFAULT NULL,
  `ec_media_lot` int(8) DEFAULT NULL,
  `label_color` varchar(255) DEFAULT NULL,
  `biocool_id_no` int(11) DEFAULT NULL,
  `proh_time_min` int(11) DEFAULT NULL,
  `start_temp` float(11,2) DEFAULT NULL,
  `start_time` time DEFAULT NULL,
  `end_temp` float(11,2) DEFAULT NULL,
  `end_time` time DEFAULT NULL,
  `time_hold_at_end_temp` int(11) DEFAULT NULL,
  `cryo_info_comments` text,
  `blast_genotype` varchar(255) DEFAULT NULL,
  `embryogeno_confirmed` tinyint(1) DEFAULT NULL,
  `ec_test_genotyped_by` varchar(255) DEFAULT NULL,
  `embryo_geno_date` date DEFAULT NULL,
  `embryo_genotype_notes` text,
  `thawing_date` date DEFAULT NULL,
  `straw_id_no` varchar(25) DEFAULT NULL,
  `recovered_no` int(11) DEFAULT NULL,
  `intact_no` int(11) DEFAULT NULL,
  `cultured_no` int(11) DEFAULT NULL,
  `blasts_no` int(11) DEFAULT NULL,
  `culture_medium` varchar(255) DEFAULT NULL,
  `culture_medium_lot` int(11) DEFAULT NULL,
  `cultured_by` varchar(255) DEFAULT NULL,
  `incubator_no` varchar(255) DEFAULT NULL,
  `ec_test_thaw_comments` text,
  `user_id` int(11) DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `fmp_id_no` int(11) DEFAULT NULL,
  `fmp_job_id_no` int(11) DEFAULT NULL,
  `fmp_ivf_id_no` int(11) DEFAULT NULL,
  `distribute_status` varchar(40) DEFAULT NULL,
  `distribute_comment` text,
  `verified` tinyint(1) DEFAULT NULL,
  `verified_by` varchar(100) DEFAULT NULL,
  `verified_time` datetime DEFAULT NULL,
  `storage_comments` text,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`) USING BTREE,
  KEY `job_id` (`job_id`) USING BTREE,
  KEY `ivf_id` (`ivf_id`) USING BTREE,
  KEY `user_id` (`user_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=8048 DEFAULT CHARSET=utf8;


