CREATE TABLE `injections` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `qc_state` varchar(45) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `colony_id` int(11) DEFAULT NULL,
  `project_id` int(11) DEFAULT NULL,
  `recharge` varchar(45) DEFAULT NULL,
  `injection_date` date DEFAULT NULL,
  `membership` varchar(45) DEFAULT NULL,
  `donor_strain` varchar(45) DEFAULT NULL,
  `donor_date_of_birth` date DEFAULT NULL,
  `stud_ids` varchar(45) DEFAULT NULL,
  `pmsg_time` time DEFAULT NULL,
  `hcg_time` time DEFAULT NULL,
  `number_mated` int(11) DEFAULT NULL,
  `number_plugged` int(11) DEFAULT NULL,
  `total_eggs_collected` int(11) DEFAULT NULL,
  `fresh_or_frozen` varchar(45) DEFAULT NULL,
  `injection_method` varchar(45) DEFAULT NULL,
  `number_injected` int(11) DEFAULT NULL,
  `number_survived` int(11) DEFAULT NULL,
  `number_transferred` varchar(10) DEFAULT NULL,
  `comments` text,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `mi_plan_id` int(11) DEFAULT NULL,
  `mi_attempt_id` int(11) DEFAULT NULL,
  `investigator` varchar(100) DEFAULT NULL,
  `es_cell_source` varchar(100) DEFAULT NULL,
  `parental_esc_line` varchar(100) DEFAULT NULL,
  `coat_color` varchar(100) DEFAULT NULL,
  `es_cell_clone` varchar(100) DEFAULT NULL,
  `esc_morphology` varchar(255) DEFAULT NULL,
  `embryos_collected_by` varchar(100) DEFAULT NULL,
  `injection_type` varchar(100) DEFAULT NULL,
  `et_by` varchar(100) DEFAULT NULL,
  `total_embryos` int(11) DEFAULT NULL,
  `total_zygotes` int(11) DEFAULT NULL,
  `pts_ko_mo` varchar(25) DEFAULT NULL,
  `injected_by` varchar(100) DEFAULT NULL,
  `number_two_cell` int(11) DEFAULT NULL,
  `number_zygotes_injected` int(11) DEFAULT NULL,
  `crispr_project_name` varchar(100) DEFAULT NULL,
  `bl_eight_cell` tinyint(1) DEFAULT NULL,
  `cr_electroporation` tinyint(1) DEFAULT NULL,
  `microinjection_injection_type` varchar(255) DEFAULT NULL,
  `fmp_id_no` int(11) DEFAULT NULL,
  `legacy_id_no` varchar(25) DEFAULT NULL,
  `inventory_vial_id` int(11) DEFAULT NULL,
  `voltage` decimal(11,2) DEFAULT NULL,
  `number_of_pulses` decimal(11,2) DEFAULT NULL,
  `pulse_duration` decimal(11,2) DEFAULT NULL,
  `pulse_width` decimal(11,2) DEFAULT NULL,
  `mrna_nuclease` varchar(255) DEFAULT NULL,
  `mrna_nuclease_concentration` decimal(11,2) DEFAULT NULL,
  `protein_nuclease` varchar(255) DEFAULT NULL,
  `protein_nuclease_concentration` decimal(11,2) DEFAULT NULL,
  `grna_concentration` decimal(11,2) DEFAULT NULL,
  `ravata_voltage` decimal(11,2) DEFAULT NULL,
  `ravata_number_of_pulses` decimal(11,2) DEFAULT NULL,
  `ravata_pulse_duration` decimal(11,2) DEFAULT NULL,
  `ravata_pulse_width` decimal(11,2) DEFAULT NULL,
  `imits_mi_attempt_id` int(11) DEFAULT NULL,
  `do_imits_update` tinyint(1) DEFAULT NULL,
  `job_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`) USING BTREE,
  KEY `fk_injections` (`project_id`) USING BTREE,
  KEY `colony_id` (`colony_id`),
  KEY `user_id` (`user_id`),
  KEY `project_id` (`project_id`),
  KEY `job_id` (`job_id`),
  KEY `injection_type` (`injection_type`)
) ENGINE=InnoDB AUTO_INCREMENT=7954 DEFAULT CHARSET=latin1;


