CREATE TABLE `inventory_vials` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `label` varchar(100) DEFAULT NULL,
  `volume` varchar(100) DEFAULT NULL,
  `inventory_location_id` int(11) DEFAULT '0',
  `inventory_vial_type_id` int(11) DEFAULT '0',
  `comments` text,
  `tissue` tinyint(1) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `sperm_cryo_id` int(11) DEFAULT NULL,
  `embryo_cryo_id` int(11) DEFAULT NULL,
  `pups` varchar(25) DEFAULT NULL,
  `qc_pass` varchar(25) DEFAULT NULL,
  `komp_vial_id_no` int(11) DEFAULT NULL,
  `komp_clone_id` int(11) DEFAULT NULL,
  `on_bench` tinyint(1) DEFAULT NULL,
  `es_cell_id` int(11) DEFAULT NULL,
  `do_not_distribute` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`) USING BTREE,
  KEY `Vial_Vial_types` (`inventory_vial_type_id`) USING BTREE,
  KEY `Vial_Locations` (`inventory_location_id`) USING BTREE,
  KEY `inventory_vials_4` (`sperm_cryo_id`) USING BTREE,
  KEY `inventory_vials_5` (`embryo_cryo_id`) USING BTREE,
  KEY `kompvial` (`komp_vial_id_no`) USING BTREE,
  KEY `user_id` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=707712 DEFAULT CHARSET=latin1;

