CREATE TABLE `ivfs` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `job_id` int(11) DEFAULT NULL,
  `ivf_date` date DEFAULT NULL,
  `background` varchar(255) DEFAULT NULL,
  `purpose` varchar(255) DEFAULT NULL,
  `membership` varchar(255) DEFAULT NULL,
  `sperm_info_donor_strain` varchar(255) DEFAULT NULL,
  `fresh_frozen` varchar(255) DEFAULT NULL,
  `sample_type` varchar(255) DEFAULT NULL,
  `sperm_cryo_id` int(11) DEFAULT NULL,
  `straw_vial_no` varchar(255) DEFAULT NULL,
  `cpa_lot_no` int(11) DEFAULT NULL,
  `centrifuge_force` varchar(255) DEFAULT NULL,
  `centrifuge_time` int(11) DEFAULT NULL,
  `collect_thaw_time` time DEFAULT NULL,
  `time_in_mbcd` time DEFAULT NULL,
  `stud_id_no` varchar(100) DEFAULT NULL,
  `stud_dob` date DEFAULT NULL,
  `abnormal_heads` decimal(11,2) DEFAULT NULL,
  `abnormal_tails` decimal(11,2) DEFAULT NULL,
  `cpa_fresh_sperm_conc` decimal(11,2) DEFAULT NULL,
  `cpa_fresh_total_motility` decimal(11,2) DEFAULT NULL,
  `cpa_fresh_rapid_motility` decimal(11,2) DEFAULT NULL,
  `cpa_fresh_prog_motality` decimal(11,2) DEFAULT NULL,
  `mbcd_sperm_conc` decimal(11,2) DEFAULT NULL,
  `mbcd_total_motality` decimal(11,2) DEFAULT NULL,
  `mbcd_rapid_motality` decimal(11,2) DEFAULT NULL,
  `mbcd_prog_motality` decimal(11,2) DEFAULT NULL,
  `sperm_analyzer` varchar(10) DEFAULT NULL,
  `epi_storage_tank` int(11) DEFAULT NULL,
  `epi_storage_rack` int(11) DEFAULT NULL,
  `epi_storage_box` int(11) DEFAULT NULL,
  `epi_storage_space` int(11) DEFAULT NULL,
  `epi_storage_vial_id_no` varchar(255) DEFAULT NULL,
  `epi_storage_code` varchar(255) DEFAULT NULL,
  `male_genotype_confirmed` tinyint(1) DEFAULT NULL,
  `geno_date` date DEFAULT NULL,
  `genotyped_by` varchar(255) DEFAULT NULL,
  `sperm_info_comments` text,
  `eggs_info_donor_strain` varchar(255) DEFAULT NULL,
  `eggs_info_genotype` varchar(255) DEFAULT NULL,
  `eggs_info_donor_dob` date DEFAULT NULL,
  `eggs_info_donor_age` varchar(255) DEFAULT NULL,
  `eggs_info_comments` text,
  `females_ordered_no` int(11) DEFAULT NULL,
  `females_out_no` int(11) DEFAULT NULL,
  `unsuperovulated_no` decimal(11,2) DEFAULT NULL,
  `pmsg_time` time DEFAULT NULL,
  `hcg_time` time DEFAULT NULL,
  `pmsg_hcg_by` varchar(255) DEFAULT NULL,
  `icsi` tinyint(1) DEFAULT NULL,
  `ivf_method` varchar(255) DEFAULT NULL,
  `laser_system` varchar(255) DEFAULT NULL,
  `pulse_duration` int(11) DEFAULT NULL,
  `laser_power` int(11) DEFAULT NULL,
  `co_culture_hrs` varchar(11) DEFAULT NULL,
  `incubator_id_no` varchar(11) DEFAULT NULL,
  `ivf_note` text,
  `two_cell_score_time` time DEFAULT NULL,
  `ivf_icsi_by` varchar(255) DEFAULT NULL,
  `ivf_icsi_info_comment` text,
  `egg_collection_time` time DEFAULT NULL,
  `icsi_end_time` time DEFAULT NULL,
  `eggs_injected_no` int(11) DEFAULT NULL,
  `eggs_survived_no` int(11) DEFAULT NULL,
  `survival_rate` decimal(11,2) DEFAULT NULL,
  `more_icsi_info_comments` text,
  `ivf_medium` varchar(255) DEFAULT NULL,
  `ivf_medium_lot` varchar(50) DEFAULT NULL,
  `ivf_medium_vendor` varchar(255) DEFAULT NULL,
  `oil_vendor` varchar(255) DEFAULT NULL,
  `oil_lot` varchar(255) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `genotype` varchar(255) DEFAULT NULL,
  `fmp_id_no` int(11) DEFAULT NULL,
  `fmp_job_id_no` int(11) DEFAULT NULL,
  `fmp_sc_id_no` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`) USING BTREE,
  KEY `job_id` (`job_id`) USING BTREE,
  KEY `sperm_cryo_id` (`sperm_cryo_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=10097 DEFAULT CHARSET=utf8;

