CREATE TABLE `qc_genotypes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `kompvialid` int(11) DEFAULT NULL,
  `started` date DEFAULT NULL,
  `finished` date DEFAULT NULL,
  `started_by` varchar(50) DEFAULT NULL,
  `finished_by` varchar(50) DEFAULT NULL,
  `pass` varchar(25) DEFAULT NULL,
  `comment` blob,
  `test5` varchar(25) DEFAULT NULL,
  `test3` varchar(25) DEFAULT NULL,
  `testcopy1` varchar(25) DEFAULT NULL,
  `testcopy1value` decimal(10,2) DEFAULT NULL,
  `testLRPCR5` varchar(25) DEFAULT NULL,
  `test_integrity5` varchar(25) DEFAULT NULL,
  `date5` date DEFAULT NULL,
  `date3` date DEFAULT NULL,
  `date_copy` date DEFAULT NULL,
  `dateLRPCR5` date DEFAULT NULL,
  `date_integrity5` date DEFAULT NULL,
  `test_genome` varchar(25) DEFAULT NULL,
  `date_genome` date DEFAULT NULL,
  `lost_y` varchar(25) DEFAULT NULL,
  `date_y` date DEFAULT NULL,
  `positive_control` varchar(25) DEFAULT NULL,
  `test_identity` varchar(25) DEFAULT NULL,
  `last_changed` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `testLRPCR3` varchar(25) DEFAULT NULL,
  `dateLRPCR3` date DEFAULT NULL,
  `test_loxp` varchar(25) DEFAULT NULL,
  `date_loxp` date DEFAULT NULL,
  `loxp_result` varchar(25) DEFAULT NULL,
  `date_loxp_result` date DEFAULT NULL,
  `prime3_loxp_result` varchar(25) DEFAULT NULL,
  `date_3prime_loxp_result` date DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `inventory_vial_id` int(11) DEFAULT NULL,
  `quality_control_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=19234 DEFAULT CHARSET=latin1;

