CREATE TABLE `recipients` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ear_mark` varchar(25) DEFAULT NULL,
  `weight` decimal(10,2) DEFAULT NULL,
  `dob` date DEFAULT NULL,
  `embryo_stage` varchar(100) DEFAULT NULL,
  `anesthetic_vol` varchar(11) DEFAULT NULL,
  `analgesic_vol` varchar(11) DEFAULT NULL,
  `cl` tinyint(1) DEFAULT NULL,
  `amp` tinyint(1) DEFAULT NULL,
  `tx_l` int(11) DEFAULT NULL,
  `tx_r` int(11) DEFAULT NULL,
  `total_tx` int(11) DEFAULT NULL,
  `male_pups` int(11) DEFAULT NULL,
  `female_pups` int(11) DEFAULT NULL,
  `total_pups` int(11) DEFAULT NULL,
  `male_mut` int(11) DEFAULT NULL,
  `female_mut` int(11) DEFAULT NULL,
  `male_wt` int(11) DEFAULT NULL,
  `female_wt` int(11) DEFAULT NULL,
  `pups_born` int(1) DEFAULT NULL,
  `embryo_transfer_id` int(11) DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  `modified` datetime DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `recipient_id_no` int(11) DEFAULT NULL,
  `comments` text,
  `et_by` varchar(10) DEFAULT NULL,
  `anesthetic_vol_type` varchar(5) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`) USING BTREE,
  KEY `recipient_embryo_transfer` (`embryo_transfer_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=27312 DEFAULT CHARSET=utf8;

