CREATE TABLE `sperm_cryos` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) DEFAULT NULL,
  `job_id` int(11) DEFAULT NULL,
  `cryo_date` date DEFAULT NULL,
  `pi_first_name` varchar(255) DEFAULT NULL,
  `pi_last_name` varchar(255) DEFAULT NULL,
  `donor_genotype` varchar(255) DEFAULT NULL,
  `donor_id_no` varchar(100) DEFAULT NULL,
  `donor_dob` date DEFAULT NULL,
  `donor_age` varchar(25) DEFAULT NULL,
  `cryo_sample_type` varchar(255) DEFAULT NULL,
  `cryo_method` varchar(255) DEFAULT NULL,
  `cryo_caps_label_color` varchar(255) DEFAULT NULL,
  `fmp_id_no` int(11) DEFAULT NULL,
  `cryo_medium` varchar(255) DEFAULT NULL,
  `cryo_cpm_lot_no` varchar(10) DEFAULT NULL,
  `cryo_mosm` int(11) DEFAULT NULL,
  `cryo_sperm_conc` decimal(11,2) DEFAULT NULL,
  `cryo_total_motility` decimal(11,2) DEFAULT NULL,
  `cryo_rapid_motility` decimal(11,2) DEFAULT NULL,
  `cryo_prog_motility` decimal(11,2) DEFAULT NULL,
  `cryo_sperm_analyser` varchar(10) DEFAULT NULL,
  `cryo_abnormal_heads` decimal(11,2) DEFAULT NULL,
  `cryo_abnormal_tails` decimal(11,2) DEFAULT NULL,
  `cryo_scored_by` varchar(255) DEFAULT NULL,
  `cryo_collected_by` varchar(255) DEFAULT NULL,
  `cryo_sc_performed_by` varchar(255) DEFAULT NULL,
  `cryo_comments` text,
  `modified` datetime DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  `recieving_date` date DEFAULT NULL,
  `donor_comments` text,
  `donor_genotype_confirmed` tinyint(1) DEFAULT NULL,
  `sperm_taqman` varchar(255) DEFAULT NULL,
  `taqman_date` date DEFAULT NULL,
  `taqman_by` varchar(255) DEFAULT NULL,
  `geno_date` date DEFAULT NULL,
  `geno_by` varchar(255) DEFAULT NULL,
  `targeted_status` varchar(255) DEFAULT NULL,
  `targeted_confirmed_date` date DEFAULT NULL,
  `targeting_confirmed_by` varchar(255) DEFAULT NULL,
  `post_sperm_conc` decimal(11,2) DEFAULT NULL,
  `post_total_motility` decimal(11,2) DEFAULT NULL,
  `post_rapid_motility` decimal(11,2) DEFAULT NULL,
  `post_prog_motility` decimal(11,2) DEFAULT NULL,
  `fmp_job_id_no` int(11) DEFAULT NULL,
  `distribute_status` varchar(40) DEFAULT NULL,
  `distribute_comment` text,
  `vapor_temperature` decimal(11,2) DEFAULT NULL,
  `incorrect_genotype` tinyint(1) DEFAULT NULL,
  `verified` tinyint(1) DEFAULT NULL,
  `verified_by` varchar(100) DEFAULT NULL,
  `verified_time` datetime DEFAULT NULL,
  `storage_comments` text,
  `pcr_results` varchar(255) DEFAULT NULL,
  `pcr_date` date DEFAULT NULL,
  `pcr_by` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`) USING BTREE,
  KEY `user_id` (`user_id`) USING BTREE,
  KEY `job_id` (`job_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=25284 DEFAULT CHARSET=utf8;

